### ISSUE TITLE
常用css

### ISSUE THREAD

**Issue by hourong88** [hourong88/blog#8]
# 常用css集合

## flex公共class
```css
.display_none {
    display: none !important;
  }

  .visibility_hidden {
    visibility: hidden;
  }

  .flex_top {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-align-items: flex-start;
    -ms-align-items: flex-start;
    align-items: flex-start;
  }

  .center {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: center;
    -ms-justify-content: center;
    justify-content: center;
  }

  .col_middle {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .col_center_middle {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    flex-direction: column;
    -webkit-justify-content: center;
    -ms-justify-content: center;
    justify-content: center;
    align-items: center;
  }

  .center_middle {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex !important;
    -webkit-align-items: center;
    -ms-align-items: center;
    align-items: center;
    -webkit-justify-content: center;
    -ms-justify-content: center;
    justify-content: center;
  }

  .space_between {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: space-between;
    -ms-justify-content: space-between;
    justify-content: space-between;
  }
  .col_space_between {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: space-between;
    -ms-justify-content: space-between;
    justify-content: space-between;
    flex-direction: column;
  }

  .space_around {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: space-around;
    -ms-justify-content: space-around;
    justify-content: space-around;
  }

  .right {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: flex-end !important;
    -ms-justify-content: flex-end !important;
    justify-content: flex-end !important;
  }
  .flex_wrap {
    flex-wrap: wrap;
    display: flex;
  }

  .cursor_pointer {
    cursor: pointer;
  }

  .common_shadow {
    box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.07);
  }

  .str_ellipsis{
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .str_ellpsis_2, .str_ellpsis_3 {
    display: -webkit-box;
    -webkit-box-orient: vertical!important;
    white-space: pre-wrap;
    word-wrap: break-word;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .str_ellpsis_2 {
    -webkit-line-clamp: 2; /*显示行数*/
  }

  .str_ellpsis_3 {
    -webkit-line-clamp: 3; /*显示行数*/
  }

  .middle {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex!important;
    -webkit-align-items: center;
    -ms-align-items: center;
    align-items: center;
  }
```

阮一峰  Flex 布局教程：语法篇:http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html?utm_source=tuicool

**Comment by hourong88** [comment]
![image](https://user-images.githubusercontent.com/35595174/172986473-0a0f5938-776e-406e-82ed-7db3bd3559bf.png)

```vue
<div class="avatar-wrapper">
            <img :src="Avatar" class="user-avatar">
            <div class="user">
              <div class="name">姓名</div>
              <div class="title" style="font-size:12px">职位</div>
            </div>
</div>
```

```css
.avatar-wrapper {
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-align-items: flex-start;
        -ms-align-items: flex-start;
        align-items: flex-start;
        margin-top: 12px;
        position: relative;

        .user-avatar {
          cursor: pointer;
          width: 35px;
          height: 35px;
          border-radius: 10px;
        }
      }

 .user {
      line-height: 40px;
      height: 40px;
      color: #fff;
      padding-left: 6px;
      .name {
        font-size: 14px;
        line-height: 20px;
        height: 20px;
        font-weight: 400;
        color: rgba(255, 255, 255, 0.85);
      }
      .title {
        font-size: 12px;
        line-height: 17px;
        height: 17px;
        font-weight: 400;
        color: rgba(255, 255, 255, 0.85);
      }
    }
```

**Comment by hourong88** [comment]
## 伪类
```css
.nav-sort li:not(:last-child) {
    border-bottom:#3e3e3e 1px solid;
}
```

**Comment by hourong88** [comment]
## transform
### 图片变换
```css
div img{ 
    cursor: pointer; 
    transition: all 0.6s; 
      } 
div img:hover{ 
    transform: scale(1.4); 
    }
```　　
 
transition: all 0.6s;　　表示所有的属性变化在0.6s的时间段内完成。
transform: scale(1.4);　　表示在鼠标放到图片上的时候图片按比例放大1.4倍。

**Comment by hourong88** [comment]
## 适配方案
以前的笔记：[PC站与H5移动站最佳适配方案](https://www.cnblogs.com/youqiancheng/p/7193393.html)

**Comment by hourong88** [comment]
## 其他css

### 高度计算
```css
min-height: calc(100vh - 160px);高度的100%减去160px

width: calc(100% - 112px); //相对宽度
```

### css乱码解决方法
css-loader版本过低

**Comment by hourong88** [comment]
## 雪碧图
雪碧图实现原理：
CSS雪碧的基本原理是把你的网站上用到的一些图片整合到一张单独的图片中，从而减少你的网站的HTTP请求数量。该图片使用CSS background和background-position属性渲染，这也就意味着你的标签变得更加复杂了，图片是在CSS中定义，而非<img>标签。

**Comment by hourong88** [comment]
## 浏览器私有属性

 -webkit-transform:rotate(-3deg); /*为Chrome/Safari*/
 -moz-transform:rotate(-3deg); /*为Firefox*/
 -ms-transform:rotate(-3deg); /*为IE*/
 -o-transform:rotate(-3deg); /*为Opera*/
 transform:rotate(-3deg);

**Comment by hourong88** [comment]
## css样式初始化
由于每个浏览器的css默认样式不尽相同，所以最简单有效的方式就是对其进行初始化，相信很多朋友都写过这样的代码，在所有CSS开始前，先把marin和padding都设为0，以防不同浏览器的显示效果不一样。
https://github.com/necolas/normalize.css

**Comment by hourong88** [comment]
## less 和 sass 异同 以及如何配置 TODO

**Comment by hourong88** [comment]
## CSS 函数 以及常用 TODO

**Comment by hourong88** [comment]
## 折叠面板折叠一半
<img width="348" alt="image" src="https://user-images.githubusercontent.com/35595174/179195729-d5f6bf78-2b39-4481-ae7a-a1c966575bb2.png">

```vue
    <!-- 样式展示 -->
      <div class="collapse" >
  <div class="collapse-list" v-for="(item, index) in searchItems">
    <div class="collapse-title space_between ">
      <div>{{ item.text }}</div>
      <div class="open" @click="toggleOpen(index)">展开</div>
    </div>
    <div class="collapse-item-list" :class="{ active: isActive[index] }">
      <div class="button-cancel" v-for="(child, index) in item.children">
        <button class="search-button" @click="starCancelClick">{{ child.Name }}</button>
      </div>
    </div>
  </div>
</div>
<!-- 样式展示 end-->

 isActive: {
        0: false,
        1: false,
        2: false,
      },

 toggleOpen(index) {
      this.isActive[index] = !this.isActive[index];
    },
```

```css
.collapse{
  height: 100%;
}
.collapse-list {
  border-top: 8px solid rgba(246, 246, 246, 1);
  padding: 8px !important;
}
.collapse-title {
  font-size: 14px;
  font-weight: 400;
  color: #111111;
  line-height: 20px;
  padding: 0.1rem !important;
  overflow: hidden;
  .open{
    font-size: 10px;
    color: #555555;
  }
}
//搜索商圈样式
.collapse-item-list {
  display: flex ;
  width: 100% ;
  flex-flow: wrap ;
  overflow: hidden;
  height: 120px;
}
.active{
  height: 100% !important;
}
r {
  color: #EE2233
}
.space_between {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-justify-content: space-between;
  -ms-justify-content: space-between;
  justify-content: space-between;
}
.button-cancel {
  text-align: center;
  max-width: 170px;

  .search-button {
    border-radius: 0.05rem;
    background: #F6F6F6;
    white-space: nowrap;
    overflow: hidden;
    margin: 0 0.08rem 0.08rem 0;
    line-height: 0.16rem;
    padding: 8px 15px;
    color: #111111;
    font-size: 0.11rem;
  }
}
```
